import { describe, it } from 'mocha'
import { parseFrcsPlotFile } from './index'
import { Length } from '@speleotica/unitized'
import { expect } from 'chai'

const data = `   123.182259
 AE20     1    1       0       0      0   153  -257   -51    85   0  20     1
 AE19     1    2     653     402   -548  1046  -587  -174    97   0 200     1
 AE18     2    3     669     449  -3002   995    94  -597   -56 250   0     1
 AE17     3    4     539    1217  -2770   497    47  -298   -28   0   0     1
 AE16     4    5     544    1230  -3441   411  -284  -246   170  60  10     1
 AE15     5    6    1679    1663  -3833     0     0  -282   283  20  10     1
 AE14     6    7    2026    2617  -3730   446   225  -446  -225   0  30     
 AE13     7    8     391    3152  -5788  -111   691     0     0 200  50     1
 AE12     8    9   -1019    2175  -4630  -369   336   221  -201  40  40     1
 AE11     9   10   -1516    1289  -3919  -348   195   610  -342  50  10     1
`

describe('parseFrcsPlotFile', () => {
  it('basic test', async function() {
    const parsed = await parseFrcsPlotFile('cdata.fr', data)
    expect(parsed).to.deep.equal({
      totalLength: Length.feet(123.182259),
      errors: [],
      shots: [
        {
          toName: 'AE20',
          isSurface: false,
          fromNumber: 1,
          toNumber: 1,
          easting: Length.feet(0),
          northing: Length.feet(0),
          elevation: Length.feet(0),
          leftEasting: Length.feet(1.53),
          leftNorthing: Length.feet(-2.57),
          rightEasting: Length.feet(-0.51),
          rightNorthing: Length.feet(0.85),
          up: Length.feet(0),
          down: Length.feet(2),
          tripNumber: 1,
        },
        {
          toName: 'AE19',
          isSurface: false,
          fromNumber: 1,
          toNumber: 2,
          easting: Length.feet(6.53),
          northing: Length.feet(4.02),
          elevation: Length.feet(-5.48),
          leftEasting: Length.feet(10.46),
          leftNorthing: Length.feet(-5.87),
          rightEasting: Length.feet(-1.74),
          rightNorthing: Length.feet(0.97),
          up: Length.feet(0),
          down: Length.feet(20),
          tripNumber: 1,
        },
        {
          toName: 'AE18',
          isSurface: false,
          fromNumber: 2,
          toNumber: 3,
          easting: Length.feet(6.69),
          northing: Length.feet(4.49),
          elevation: Length.feet(-30.02),
          leftEasting: Length.feet(9.95),
          leftNorthing: Length.feet(0.94),
          rightEasting: Length.feet(-5.97),
          rightNorthing: Length.feet(-0.56),
          up: Length.feet(25),
          down: Length.feet(0),
          tripNumber: 1,
        },
        {
          toName: 'AE17',
          isSurface: false,
          fromNumber: 3,
          toNumber: 4,
          easting: Length.feet(5.39),
          northing: Length.feet(12.17),
          elevation: Length.feet(-27.7),
          leftEasting: Length.feet(4.97),
          leftNorthing: Length.feet(0.47),
          rightEasting: Length.feet(-2.98),
          rightNorthing: Length.feet(-0.28),
          up: Length.feet(0),
          down: Length.feet(0),
          tripNumber: 1,
        },
        {
          toName: 'AE16',
          isSurface: false,
          fromNumber: 4,
          toNumber: 5,
          easting: Length.feet(5.44),
          northing: Length.feet(12.3),
          elevation: Length.feet(-34.41),
          leftEasting: Length.feet(4.11),
          leftNorthing: Length.feet(-2.84),
          rightEasting: Length.feet(-2.46),
          rightNorthing: Length.feet(1.7),
          up: Length.feet(6),
          down: Length.feet(1),
          tripNumber: 1,
        },
        {
          toName: 'AE15',
          isSurface: false,
          fromNumber: 5,
          toNumber: 6,
          easting: Length.feet(16.79),
          northing: Length.feet(16.63),
          elevation: Length.feet(-38.33),
          leftEasting: Length.feet(0),
          leftNorthing: Length.feet(0),
          rightEasting: Length.feet(-2.82),
          rightNorthing: Length.feet(2.83),
          up: Length.feet(2),
          down: Length.feet(1),
          tripNumber: 1,
        },
        {
          toName: 'AE14',
          isSurface: false,
          fromNumber: 6,
          toNumber: 7,
          easting: Length.feet(20.26),
          northing: Length.feet(26.17),
          elevation: Length.feet(-37.3),
          leftEasting: Length.feet(4.46),
          leftNorthing: Length.feet(2.25),
          rightEasting: Length.feet(-4.46),
          rightNorthing: Length.feet(-2.25),
          up: Length.feet(0),
          down: Length.feet(3),
          tripNumber: null,
        },
        {
          toName: 'AE13',
          isSurface: false,
          fromNumber: 7,
          toNumber: 8,
          easting: Length.feet(3.91),
          northing: Length.feet(31.52),
          elevation: Length.feet(-57.88),
          leftEasting: Length.feet(-1.11),
          leftNorthing: Length.feet(6.91),
          rightEasting: Length.feet(0),
          rightNorthing: Length.feet(0),
          up: Length.feet(20),
          down: Length.feet(5),
          tripNumber: 1,
        },
        {
          toName: 'AE12',
          isSurface: false,
          fromNumber: 8,
          toNumber: 9,
          easting: Length.feet(-10.19),
          northing: Length.feet(21.75),
          elevation: Length.feet(-46.3),
          leftEasting: Length.feet(-3.69),
          leftNorthing: Length.feet(3.36),
          rightEasting: Length.feet(2.21),
          rightNorthing: Length.feet(-2.01),
          up: Length.feet(4),
          down: Length.feet(4),
          tripNumber: 1,
        },
        {
          toName: 'AE11',
          isSurface: false,
          fromNumber: 9,
          toNumber: 10,
          easting: Length.feet(-15.16),
          northing: Length.feet(12.89),
          elevation: Length.feet(-39.19),
          leftEasting: Length.feet(-3.48),
          leftNorthing: Length.feet(1.95),
          rightEasting: Length.feet(6.1),
          rightNorthing: Length.feet(-3.42),
          up: Length.feet(5),
          down: Length.feet(1),
          tripNumber: 1,
        },
      ],
    })
  })
})
